"""Add cost_price and rename price to selling_price in Product

Revision ID: c4ed818b444d
Revises: 2ad558ae5b13
Create Date: 2025-09-04 18:54:51.762311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4ed818b444d'
down_revision = '2ad558ae5b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.drop_column('selling_price')
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
